spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema:
  datasource:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:person.sql
# application.yml

logging:
  level:
    org.springframework.batch.item.database.JdbcPagingItemReader: DEBUG
